feature: 'mels'
sample_rate: 16000
n_mels: 32
fmin: 0
fmax: 8000
n_fft: 512
hop_length: 256
augmentations: 5
preprocessed_valid_path: './data/preprocessed_valid.csv'
preprocess_out: 'preprocess'
feature_out: 'features'
sample_count: 3000